//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadMusic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DownloadMusic.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        public static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Krystsina_Kasko\Documents\Visual Studio 2015\Projects\DownloadMusic\packages\Selenium.WebDriver.ChromeDriver.2.27.0\driver.
        /// </summary>
        public static string ChromeDriverPath {
            get {
                return ResourceManager.GetString("ChromeDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clubnie.
        /// </summary>
        public static string ClubRingtones {
            get {
                return ResourceManager.GetString("ClubRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Krystsina_Kasko\Documents\Visual Studio 2015\Projects\DownloadMusic\packages\FireFoxDriver.
        /// </summary>
        public static string FFDriverPath {
            get {
                return ResourceManager.GetString("FFDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarubejnie.
        /// </summary>
        public static string ForeignRingtones {
            get {
                return ResourceManager.GetString("ForeignRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Krystsina_Kasko\Documents\Visual Studio 2015\Projects\DownloadMusic\packages\IEDriver.
        /// </summary>
        public static string IEDriverPath {
            get {
                return ResourceManager.GetString("IEDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retro-80-90.
        /// </summary>
        public static string RetroRingtones {
            get {
                return ResourceManager.GetString("RetroRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rock.
        /// </summary>
        public static string RockRingtones {
            get {
                return ResourceManager.GetString("RockRingtones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to russian.
        /// </summary>
        public static string RussianRingtones {
            get {
                return ResourceManager.GetString("RussianRingtones", resourceCulture);
            }
        }
    }
}
